### 회원가입
POST https://fe-project-cowokers.vercel.app/20-3/auth/signup
Content-Type: application/json

{
  "email": "testuser126@test.com",
  "nickname": "테스트계정-4",
  "password": "testuser126@",
  "passwordConfirmation": "testuser126@"
}

### 로그인
POST https://fe-project-cowokers.vercel.app/20-3/auth/signin
Content-Type: application/json

{
  "email": "testuser123@test.com",
  "password": "testuser123@"
}

### 회원정보 수정
PATCH https://fe-project-cowokers.vercel.app/20-3/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mjc1NCwidGVhbUlkIjoiMjAtMyIsInNjb3BlIjoiYWNjZXNzIiwiaWF0IjoxNzcwMDQ4MDU4LCJleHAiOjE3NzAwNTE2NTgsImlzcyI6InNwLWNvd29ya2VycyJ9.JC84-zijVH6LfvGYGlJqGh6a8d4SRfOxozUzA4sKFmI

{
  "image": "https://randomuser.me/api/portraits/men/12.jpg"
}

// 회원정보
# {
#   "user": {
#     "id": 2750,
#     "nickname": "테스트계정",
#     "createdAt": "2026-01-31T16:04:40+09:00",
#     "updatedAt": "2026-01-31T16:04:40+09:00",
#     "image": null,
#     "teamId": "20-3",
#     "email": "testuser123@test.com"
#   },
#   "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mjc1MCwidGVhbUlkIjoiMjAtMyIsInNjb3BlIjoiYWNjZXNzIiwiaWF0IjoxNzY5ODQzMTkyLCJleHAiOjE3Njk4NDY3OTIsImlzcyI6InNwLWNvd29ya2VycyJ9.TfDzeY6JWrDgp5CyqqmJmY_ldP4NlinfbsDlkrjz53c",
#   "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mjc1MCwidGVhbUlkIjoiMjAtMyIsInNjb3BlIjoicmVmcmVzaCIsImlhdCI6MTc2OTg0MzE5MiwiZXhwIjoxNzcwNDQ3OTkyLCJpc3MiOiJzcC1jb3dvcmtlcnMifQ.mpxYjy7UFnSpzR3wfXbXh5jpTS07qtLcpX7pscw7hro"
# }


### 그룹(팀) 생성

POST https://fe-project-cowokers.vercel.app/20-3/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mjc1MCwidGVhbUlkIjoiMjAtMyIsInNjb3BlIjoiYWNjZXNzIiwiaWF0IjoxNzY5ODQzMTkyLCJleHAiOjE3Njk4NDY3OTIsImlzcyI6InNwLWNvd29ya2VycyJ9.TfDzeY6JWrDgp5CyqqmJmY_ldP4NlinfbsDlkrjz53c

{
  "image": "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=400&h=400&fit=crop",
  "name": "팀 베타"
}


### 그룹(팀) 목록 조회
GET https://fe-project-cowokers.vercel.app/20-3/user/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mjc1MCwidGVhbUlkIjoiMjAtMyIsInNjb3BlIjoiYWNjZXNzIiwiaWF0IjoxNzcwMTQzNDMwLCJleHAiOjE3NzAxNDcwMzAsImlzcyI6InNwLWNvd29ya2VycyJ9.NQhQf87dM0pAUIAdpl5Rs27JFAIKN3_7CY67H5Ov1Qg


### 그룹(팀) 삭제
DELETE https://fe-project-cowokers.vercel.app/20-3/groups/3812
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mjc1MCwidGVhbUlkIjoiMjAtMyIsInNjb3BlIjoiYWNjZXNzIiwiaWF0IjoxNzY5ODQzMTkyLCJleHAiOjE3Njk4NDY3OTIsImlzcyI6InNwLWNvd29ya2VycyJ9.TfDzeY6JWrDgp5CyqqmJmY_ldP4NlinfbsDlkrjz53c


### 할 일 생성
POST https://fe-project-cowokers.vercel.app/20-3/groups/3810/task-lists
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mjc1MCwidGVhbUlkIjoiMjAtMyIsInNjb3BlIjoiYWNjZXNzIiwiaWF0IjoxNzcwMDEwOTc0LCJleHAiOjE3NzAwMTQ1NzQsImlzcyI6InNwLWNvd29ya2VycyJ9.t86UDahxRl7ws1Ch2cagrLMYqgCf5v-Cz4UocYx_Jdo

{
  "name": "테스트 할 일-3"
}

### 할 일 항목 생성
POST https://fe-project-cowokers.vercel.app/20-3/groups/3810/task-lists/5284/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mjc1MCwidGVhbUlkIjoiMjAtMyIsInNjb3BlIjoiYWNjZXNzIiwiaWF0IjoxNzcwMDU5MzYzLCJleHAiOjE3NzAwNjI5NjMsImlzcyI6InNwLWNvd29ya2VycyJ9.TsL7YZ0M2pbss5m70IVM4JHmG7Ky5EOlAN5rAROwdpU

{
  "name": "매달 생성 테스트",
  "description": "MONTHLY TASK",
  "startDate": "2026-02-02T00:00:00Z",
  "frequencyType": "MONTHLY",
  "monthDay": 2
}


### 할 일 항목 조회
GET https://fe-project-cowokers.vercel.app/20-3/groups/3810/task-lists/5284/tasks?date=2026-03-02
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mjc1MCwidGVhbUlkIjoiMjAtMyIsInNjb3BlIjoiYWNjZXNzIiwiaWF0IjoxNzcwMTQzNDMwLCJleHAiOjE3NzAxNDcwMzAsImlzcyI6InNwLWNvd29ya2VycyJ9.NQhQf87dM0pAUIAdpl5Rs27JFAIKN3_7CY67H5Ov1Qg

### 할 일 항목 조회
GET https://fe-project-cowokers.vercel.app/20-3/groups/3810/tasks?date=2026-03-02
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mjc1MCwidGVhbUlkIjoiMjAtMyIsInNjb3BlIjoiYWNjZXNzIiwiaWF0IjoxNzcwMDU5MzYzLCJleHAiOjE3NzAwNjI5NjMsImlzcyI6InNwLWNvd29ya2VycyJ9.TsL7YZ0M2pbss5m70IVM4JHmG7Ky5EOlAN5rAROwdpU



### 그룹에 유저 생성
POST https://fe-project-cowokers.vercel.app/20-3/groups/3810/member
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mjc1MCwidGVhbUlkIjoiMjAtMyIsInNjb3BlIjoiYWNjZXNzIiwiaWF0IjoxNzcwMDQ3MjY0LCJleHAiOjE3NzAwNTA4NjQsImlzcyI6InNwLWNvd29ya2VycyJ9.-PjSPPHoyVfVQjzUrDtUBa-EP0vKAoVl5cKBfsDkIeo

{
  "userEmail": "testuser126@test.com"
}

### 할 일 항목 수정
PATCH https://fe-project-cowokers.vercel.app/20-3/groups/3810/task-lists/5284/tasks/29333
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Mjc1MCwidGVhbUlkIjoiMjAtMyIsInNjb3BlIjoiYWNjZXNzIiwiaWF0IjoxNzcwMDU5MzYzLCJleHAiOjE3NzAwNjI5NjMsImlzcyI6InNwLWNvd29ya2VycyJ9.TsL7YZ0M2pbss5m70IVM4JHmG7Ky5EOlAN5rAROwdpU

{
  "done": true
}